export type AuthProfileKind = "kimi-api-key" | "openai-api-key" | "openai-compatible" | "codex-sdk" | "gpt-auth";

export type HarnessPurpose =
  | "research"
  | "product_decision"
  | "implementation"
  | "release"
  | "bootstrap_handoff"
  | "local_only";

export interface AuthProfileInput {
  kind: AuthProfileKind;
  model?: string;
  baseURL?: string;
  apiKeyEnv?: string;
  purpose?: HarnessPurpose;
}

export interface AuthProfile {
  kind: AuthProfileKind;
  backend: "openai-compatible" | "codex-local-agent";
  model: string;
  baseURL?: string;
  apiKeyEnv?: string;
  allowlistHosts: string[];
  envPlan: Record<string, string>;
  packageName?: string;
}

export interface NaiaServiceManifest {
  schemaVersion: "0.1.0";
  name: string;
  description: string;
  persona: {
    systemPrompt: string;
  };
  llm: {
    backend: string;
    model: string;
    baseURL?: string;
  };
  memory: {
    binding: "in-memory" | "none" | "alpha-memory";
  };
}

const KIMI_DEFAULT_BASE_URL = "https://api.kimi.com/coding/v1";
const KIMI_DEFAULT_MODEL = "kimi-for-coding";
const OPENAI_DEFAULT_BASE_URL = "https://api.openai.com/v1";
const OPENAI_DEFAULT_MODEL = "gpt-4.1";
const CODEX_DEFAULT_MODEL = "gpt-5.5";
const AUTH_PROFILE_KINDS = new Set<AuthProfileKind>([
  "kimi-api-key",
  "openai-api-key",
  "openai-compatible",
  "codex-sdk",
  "gpt-auth",
]);

export function resolveAuthProfile(input: AuthProfileInput): AuthProfile {
  assertAuthProfileKind(input.kind);
  if (input.kind === "codex-sdk" || input.kind === "gpt-auth") {
    return {
      kind: input.kind,
      backend: "codex-local-agent",
      model: input.model ?? CODEX_DEFAULT_MODEL,
      allowlistHosts: [],
      envPlan: {},
      packageName: "@openai/codex-sdk",
    };
  }

  const defaults = apiKeyDefaultsFor(input.kind);
  const apiKeyEnvOverride = nonEmpty(input.apiKeyEnv);
  const endpoint = resolveProviderEndpoint({
    kind: input.kind,
    requestedBaseURL: input.baseURL,
    defaultBaseURL: defaults.baseURL,
    apiKeyEnvOverride,
  });

  const model = nonEmpty(input.model) ?? defaults.model;
  const apiKeyEnv = assertEnvReference(apiKeyEnvOverride ?? defaults.apiKeyEnv);
  const { baseURL, host } = endpoint;

  return {
    kind: input.kind,
    backend: "openai-compatible",
    model,
    baseURL,
    apiKeyEnv,
    allowlistHosts: [host],
    envPlan: {
      NAIA_SERVICE_API_KEY: `$${apiKeyEnv}`,
      NAIA_ALLOW_MANIFEST_BASEURL_HOSTS: host,
    },
  };
}

export function buildNaiaServiceManifest(profile: AuthProfile): NaiaServiceManifest {
  if (profile.backend === "codex-local-agent") {
    throw new Error("codex-local-agent profiles use @openai/codex-sdk and do not emit naia-agent service manifests");
  }

  const llm: NaiaServiceManifest["llm"] = {
    backend: profile.backend,
    model: profile.model,
  };
  if (profile.baseURL) {
    llm.baseURL = assertTrustedBaseURL(profile.baseURL).baseURL;
  }

  return {
    schemaVersion: "0.1.0",
    name: profile.kind === "kimi-api-key"
      ? "naia-carabiner-kimi"
      : profile.kind === "openai-api-key"
        ? "naia-carabiner-openai-api"
        : "naia-carabiner-openai-compatible",
    description: "naia-agent coding harness profile generated by naia-carabiner",
    persona: {
      systemPrompt: [
        "You are operating through naia-agent.",
        "Follow the local harness classification, keep secrets out of manifests,",
        "and treat KIMI/OpenAI-compatible calls as operator-approved external LLM calls.",
      ].join(" "),
    },
    llm,
    memory: {
      binding: "in-memory",
    },
  };
}

export function redactEnvPlan(envPlan: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(envPlan).map(([key, value]) => [
      key,
      shouldRedact(key, value) ? "<redacted>" : value,
    ]),
  );
}

export function formatShellEnvPlan(envPlan: Record<string, string>): string[] {
  return Object.entries(redactEnvPlan(envPlan)).map(([key, value]) => {
    const envRef = value.match(/^\$([A-Z_][A-Z0-9_]*)$/);
    if (envRef) return `export ${key}="\${${envRef[1]}}"`;
    return `export ${key}=${shellQuote(value)}`;
  });
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function apiKeyDefaultsFor(kind: AuthProfileKind): { model: string; baseURL: string; apiKeyEnv: string } {
  if (kind === "kimi-api-key") {
    return {
      model: KIMI_DEFAULT_MODEL,
      baseURL: KIMI_DEFAULT_BASE_URL,
      apiKeyEnv: "KIMI_API_KEY",
    };
  }

  return {
    model: OPENAI_DEFAULT_MODEL,
    baseURL: OPENAI_DEFAULT_BASE_URL,
    apiKeyEnv: "OPENAI_API_KEY",
  };
}

function resolveProviderEndpoint(input: {
  kind: AuthProfileKind;
  requestedBaseURL?: string;
  defaultBaseURL: string;
  apiKeyEnvOverride?: string;
}): { baseURL: string; host: string } {
  const defaultEndpoint = assertTrustedBaseURL(input.defaultBaseURL);
  const requestedBaseURL = nonEmpty(input.requestedBaseURL);
  if (!requestedBaseURL) return defaultEndpoint;

  const requestedEndpoint = assertTrustedBaseURL(requestedBaseURL);
  if (isFixedProviderProfileKind(input.kind) && requestedEndpoint.baseURL !== defaultEndpoint.baseURL) {
    throw new Error(`${input.kind} uses a fixed provider endpoint; use openai-compatible for custom baseURL`);
  }

  if (input.kind === "openai-compatible"
    && requestedEndpoint.baseURL !== defaultEndpoint.baseURL
    && !input.apiKeyEnvOverride) {
    throw new Error("custom openai-compatible baseURL requires apiKeyEnv");
  }

  return requestedEndpoint;
}

function isFixedProviderProfileKind(kind: AuthProfileKind): boolean {
  return kind === "kimi-api-key" || kind === "openai-api-key";
}

function nonEmpty(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

function assertAuthProfileKind(kind: string): asserts kind is AuthProfileKind {
  if (!AUTH_PROFILE_KINDS.has(kind as AuthProfileKind)) {
    throw new Error("unsupported auth profile kind");
  }
}

function assertEnvReference(value: string): string {
  if (!/^[A-Z_][A-Z0-9_]*$/.test(value)) {
    throw new Error("apiKeyEnv must be an environment variable name");
  }
  return value;
}

function assertTrustedBaseURL(value: string): { baseURL: string; host: string } {
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw new Error("baseURL must be a valid URL");
  }

  if (parsed.username || parsed.password) {
    throw new Error("baseURL must not include embedded credentials");
  }

  if (parsed.protocol !== "https:" && parsed.protocol !== "http:") {
    throw new Error("baseURL must use http or https");
  }

  if (parsed.protocol === "http:" && !isLoopbackHostname(parsed.hostname)) {
    throw new Error("baseURL must use https unless the host is local loopback");
  }

  if (!parsed.hostname) {
    throw new Error("baseURL must include a host");
  }

  return {
    baseURL: parsed.href.endsWith("/") ? parsed.href.slice(0, -1) : parsed.href,
    host: parsed.host,
  };
}

function isLoopbackHostname(hostname: string): boolean {
  const normalized = hostname.toLowerCase();
  return normalized === "localhost"
    || normalized === "[::1]"
    || normalized === "::1"
    || normalized.startsWith("127.");
}

function shouldRedact(key: string, value: string): boolean {
  if (value.startsWith("$")) return false;
  if (/KEY|SECRET|TOKEN|PASSWORD/i.test(key)) return true;
  return /^(sk-|sk_|eyJ|moonshot-|kimi-)/i.test(value);
}
